language: go
go:
  - 1.5
  - tip
sudo: true
before_install:
  - wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre2-10.20.tar.gz -O /tmp/pcre2-10.20.tar.gz
  - cd /tmp && tar -xvzf pcre2-10.20.tar.gz && cd /tmp/pcre2-10.20 && ./configure --enable-pcre2-32 --disable-pcre2-8 --prefix=/usr && sudo make install
install:
  - cd $HOME/gopath/src/github.com/lestrrat/go-pcre2
  - go get -t -v ./...
script:
  - cd $HOME/gopath/src/github.com/lestrrat/go-pcre2
  - go test -v ./...
